#!/bin/sh

# Copyright 2008, 2009, 2010, 2013  Patrick J. Volkerding, Sebeka, MN, USA
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


VERSION=${VERSION:-v8a}
BUILD=${BUILD:-2}

# Automatically determine the architecture we're building on:
if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) export ARCH=i486 ;;
    arm*) export ARCH=arm ;;
    # Unless $ARCH is already set, use uname -m for all other archs:
       *) export ARCH=$( uname -m ) ;;
  esac
fi

case "${HOST_TRIPLET}" in
  i686-w64-mingw32)
    LIBDIRSUFFIX=""
    ;;
  x86_64-w64-mingw32)
    LIBDIRSUFFIX="64"
    ;;
esac

NUMJOBS=${NUMJOBS:-" -j7 "}

CWD=$(pwd)
TMP=${TMP:-/tmp}
PKG=$TMP/package-libjpeg

rm -rf $PKG
mkdir -p $TMP $PKG

cd $TMP
rm -rf jpeg-$(echo $VERSION | cut -f 2 -d v)
tar xvf $CWD/jpegsrc.${VERSION}.tar.?z* || exit 1
cd jpeg-$(echo $VERSION | cut -f 2 -d v)

chown -R root:root .
find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
  -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;

zcat $CWD/jpeg.CVE-2013-6629.diff.gz | patch -p1 --verbose || exit 1

CFLAGS="-O2" \
./configure \
  --prefix=/${PREFIX} \
  --mandir=/${PREFIX}/man \
  --libdir=/${PREFIX}/lib${LIBDIRSUFFIX} \
  --disable-static \
  --host=${HOST_TRIPLET}

make $NUMJOBS || make || exit 1
make install DESTDIR=$PKG

rm -f $PKG/$PREFIX/lib${LIBDIRSUFFIX}/libjpeg.a

# Strip binaries:
( cd $PKG
  find . | xargs file | egrep "executable|shared object" | grep ${HOST_EXE_FORMAT} | cut -f 1 -d : | xargs ${HOST_STRIP} --strip-unneeded 2> /dev/null
)

# Compress and link manpages, if any:
if [ -d $PKG/${PREFIX}/man ]; then
  ( cd $PKG/${PREFIX}/man
    for manpagedir in $(find . -type d -name "man*") ; do
      ( cd $manpagedir
        for eachpage in $( find . -type l -maxdepth 1) ; do
          ln -s $( readlink $eachpage ).gz $eachpage.gz
          rm $eachpage
        done
        gzip -9 *.?
      )
    done
  )
fi

mkdir -p $PKG/${PREFIX}/doc/libjpeg-$VERSION
cp -a README $PKG/${PREFIX}/doc/libjpeg-$VERSION

cat ${CWD}/libjpeg.yypkg.script | sed \
  -e "s/%{PKG}/libjpeg/" \
  -e "s/%{HST}/${HOST_TRIPLET}/" \
  -e "s/%{TGT}//" \
  -e "s/%{VER}/${VERSION}/" \
  -e "s/%{BUILD}/${BUILD}/" \
  -e "s/%{DESCR}/${DESCR:-"No description"}/" \
  | makeypkg -o ${YYOUTPUT} -script - "${PKG}/${PREFIX}"

